version: "3.4"

services:
  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DATABASE_URL: "postgres://postgres:postgres@db:5432/vormir?sslmode=disable"
    volumes:
      - ".:/go/src/app"
    depends_on:
      - db

  db:
    image: "postgres:13.3-alpine"
    environment:
      POSTGRES_PASSWORD: postgres
      # auto-set password for dip psql
      PGPASSWORD: postgres
    volumes:
      - "postgres:/var/lib/postgresql/data"

volumes:
  postgres:
